name: web-capture-bot

networks:
  app-network:

services:
  web-capture-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TELEGRAM_API_URL: "http://bot-api-server:8081"
      WEBHOOK_LISTEN_ADDR: "0.0.0.0:8080"
      WEBHOOK_URL: "http://web-capture-bot:8080"
    networks:
      - app-network

  bot-api-server:
    image: aiogram/telegram-bot-api
    restart: always
    env_file:
      - .env
    networks:
      - app-network
